version: "3.9"

volumes:
  local-postgres-data:

services:
  todo_app_web:
    image: havardox/todo_app_web
    container_name: todo_app_web
    restart: "no"
    build:
      context: .
      dockerfile: ./compose/todo_app_web/Dockerfile
      target: base
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"
    env_file:
      - .envs/todo_app_web/dev.env

    depends_on:
      - todo_app_db

  todo_app_db:
    image: postgres:13.5-alpine
    container_name: todo_app_db
    restart: "no"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
    - "5432:5432"
    volumes:
      # - ./compose/postgres/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - local-postgres-data:/var/lib/postgresql/data
    env_file:
      - .envs/todo_app_db/dev.env
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13.5-alpine
  #   container_name: todo_app_db
  #   restart: "no"
  #   command: ["postgres", "-c", "log_statement=all"]
  #   ports:
  #   - "5432:5432"
  #   volumes:
  #     # - ./compose/postgres/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  #     - local-postgres-data:/var/lib/postgresql/data
  #   env_file:
  #     - .envs/db/dev.env